# Generated by Django 6.1.1 on 2026-09-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='category_title')),
                ('descriptin', models.TextField(blank=True, max_length=500, null=True, verbose_name='category_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='category_creator')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='form_title')),
                ('descriptin', models.TextField(blank=True, max_length=500, null=True, verbose_name='form_description')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('is_public', models.BooleanField(default=True, verbose_name='is_form_public?')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='form_password')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_form_deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='form.category', verbose_name='registered_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL, verbose_name='form_creator')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='question_text')),
                ('question_type', models.CharField(choices=[('text', 'short_text'), ('textarea', 'long_text'), ('radio', 'single_choice'), ('checkbox', 'multi_choices'), ('dropdown', 'dropdown')], max_length=20)),
                ('is_required', models.BooleanField(default=True, verbose_name='is_response_required?')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='depiction_order')),
                ('question_options', models.JSONField(blank=True, default=list, help_text='options list for multi_choices questions ', null=True, verbose_name='options')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.form', verbose_name='related_form')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('form', 'order'), name='unique_question_order_per_form')],
            },
        ),
    ]
