# Generated by Django 6.1.1 on 2026-09-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptin',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='descriptin',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='form',
            name='category',
        ),
        migrations.AddField(
            model_name='form',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='forms', to='form.category', verbose_name='registered_category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'پاراگراف'), ('number', 'عدد'), ('select', 'لیست کشویی'), ('radio', 'تک گزینه ای'), ('checkbox', 'چند گزینه ای')], max_length=20, verbose_name='question_type'),
        ),
    ]
