<<<<<<< HEAD
# Generated by Django 6.1.1 on 2026-10-02 07:47

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.db.models.deletion
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_rename_descriptin_category_description_and_more'),
<<<<<<< HEAD
        ('process', '0002_rename_descriptin_process_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'در حال تکمیل'), ('completed', 'تکمیل شده')], default='in_progress', max_length=20)),
                ('current_step_order', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
<<<<<<< HEAD
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='process.process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_executions', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('process_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submission.processexecution')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.question')),
<<<<<<< HEAD
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submission.formsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('form_submission', 'question'), name='uniq_answer_per_question_in_submission'), models.CheckConstraint(condition=models.Q(models.Q(('value_json__isnull', True), ('value_number__isnull', True), ('value_text__isnull', False)), models.Q(('value_json__isnull', True), ('value_number__isnull', False), ('value_text__isnull', True)), models.Q(('value_json__isnull', False), ('value_number__isnull', True), ('value_text__isnull', True)), _connector='OR'), name='answer_exactly_one_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='processexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('process', 'user'), name='uniq_active_execution_per_user_process'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', '-submitted_at'], name='submission__form_id_294def_idx'),
        ),
        migrations.AddConstraint(
            model_name='formsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('process_execution__isnull', False)), fields=('process_execution', 'form'), name='uniq_form_per_process_execution'),
        ),
=======
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.form')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
    ]
