# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0002_rename_descriptin_process_description_and_more'),
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='form_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submission.formsubmission'),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='process.process'),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='process_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submission.processexecution'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('form_submission', 'question'), name='uniq_answer_per_question_in_submission'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_json__isnull', True), ('value_number__isnull', True), ('value_text__isnull', False)), models.Q(('value_json__isnull', True), ('value_number__isnull', False), ('value_text__isnull', True)), models.Q(('value_json__isnull', False), ('value_number__isnull', True), ('value_text__isnull', True)), _connector='OR'), name='answer_exactly_one_value'),
        ),
        migrations.AddConstraint(
            model_name='processexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('process', 'user'), name='uniq_active_execution_per_user_process'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', '-submitted_at'], name='submission__form_id_294def_idx'),
        ),
        migrations.AddConstraint(
            model_name='formsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('process_execution__isnull', False)), fields=('process_execution', 'form'), name='uniq_form_per_process_execution'),
        ),
    ]
