# Generated by Django 6.1.1 on 2026-09-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='process_title')),
                ('descriptin', models.TextField(blank=True, max_length=500, null=True, verbose_name='process_description')),
                ('process_type', models.CharField(choices=[('linear', 'step_by_step'), ('non_linear', 'flexible')], max_length=20)),
                ('is_public', models.BooleanField(default=True, verbose_name='is_process_public?')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='process_password')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_process_deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='form.category', verbose_name='process_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_process', to=settings.AUTH_USER_MODEL, verbose_name='process_creator')),
            ],
            options={
                'verbose_name': 'process',
                'verbose_name_plural': 'processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='process_step')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_in_process', to='form.form', verbose_name='related_form')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='process.process', verbose_name='process')),
            ],
            options={
                'verbose_name': 'process_step',
                'verbose_name_plural': 'process_steps',
                'ordering': ['process', 'step_order'],
                'constraints': [models.UniqueConstraint(fields=('process', 'step_order'), name='unique_process_step_order'), models.UniqueConstraint(fields=('process', 'form'), name='unique_form_process')],
            },
        ),
    ]
