# Generated by Django 6.1.1 on 2026-09-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_descriptin_category_description_and_more'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='descriptin',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='process',
            name='category',
        ),
        migrations.AddField(
            model_name='process',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='processes', to='form.category', verbose_name='process_category'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_type',
            field=models.CharField(choices=[('linear', 'ترتیبی '), ('free', 'آزاد')], max_length=20, verbose_name='process_type'),
        ),
    ]
