<<<<<<< HEAD
# Generated by Django 6.1.1 on 2026-10-02 07:47

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 6.1.1 on 2026-09-30 20:08

>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('form', 'form'), ('process', 'process')], default='form', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
            ],
        ),
        migrations.CreateModel(
            name='VisitLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('visitor_ip', models.GenericIPAddressField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 14cb064e6b46a3bda1ebf682215ebb0ea8ebf1b0
            ],
        ),
    ]
